### ISSUE TITLE
ScrollLock and nvdaCancel() 

### ISSUE THREAD

**Issue by ghost** [hi5/nvda-autohotkey#3]
Hi,
I have the following script

ScrollLock::
nvdaCancel()
return

However, pressingScrollLock and 
customized combination based on ScrollLock
nvda still report ScrollLock is on or off.

any possible solution for that?
thanks.

**Comment by hi5** [comment]
Adding a dollar sign in front of it probably does the trick:

$ScrollLock::
nvdaCancel()
Return

If you still need to be able to turn scrollock on or off you can setup another hotkey and simply use the SetScrollLockState command, more information here:
https://www.autohotkey.com/docs/commands/SetNumScrollCapsLockState.htm

**Comment by ghost** [comment]
Oh, many thanks.
Before I have only tried adding $ sign and it doesn't work.
Now I added SetScrollLockState, AlwaysOff and nvda will not speak the message, many thanks.
